const express = require('express')
const router = express.Router()
const auth = require('../middleware/auth')
const isAdmin = require('../middleware/isAdmin')
const newsController = require('../controllers/newsController')
const urlencodedParser = require('../middleware/urlencodedParser')
const file = require('../middleware/file')
const jsonParser = express.json();

router.get('/', newsController.GetNews)
router.get('/get/:id', newsController.GetThisPost)

router.get('/getSearch/:search', urlencodedParser, newsController.GetSearch)
router.get('/settings', isAdmin, auth, newsController.GetSettings)
// router.get('/settings/create', isAdmin, auth, newsController.GetCreateSettings)
router.get('/create/post', isAdmin, auth, newsController.GetCreate)
router.get('/edit/:id', isAdmin, auth, newsController.GetEdit)
router.get('/create/category', isAdmin, auth, newsController.GetCreateCategory)
router.get('/categories', isAdmin, auth, newsController.GetCategories)
router.get('/GetEditSettings/:key', isAdmin, auth, newsController.GetEditSettings)
router.get('/watchLater', auth, urlencodedParser, newsController.GetWatchLater)
router.get('/newTag', auth, isAdmin, newsController.GetNewTag)

router.post('/create/tag', auth, isAdmin, urlencodedParser, newsController.CreateTag)
router.post('/search', urlencodedParser, newsController.search)
router.post('/SetViews', jsonParser, newsController.SetViews)
router.post('/watchLater', auth, jsonParser, urlencodedParser, newsController.watchLater)
router.post('/like', auth, jsonParser, urlencodedParser, newsController.like)
router.post('/deleteComment', auth, jsonParser, newsController.DeleteComment)
router.post('/EditComment/:id', auth, jsonParser, newsController.EditThisComment)
router.post('/newComment', auth, jsonParser, urlencodedParser, newsController.newComment)
router.post('/settings/serch',isAdmin, auth, urlencodedParser, newsController.GetSearchNews)
router.post('/editSettings', isAdmin, auth, urlencodedParser, newsController.editSettings)
// router.post('/newSettings', isAdmin, auth, urlencodedParser, newsController.CreateSettings)
router.post('/newCategory', isAdmin, auth, urlencodedParser, newsController.CreateCategory)
router.post('/newPost', isAdmin, auth, urlencodedParser, file.upload.single("postUrl"), newsController.CreateNews)
router.post('/edit', isAdmin, auth, urlencodedParser, file.upload.single("postUrl"), newsController.EditNews)
router.post('/delete/post/:id', isAdmin, auth, urlencodedParser, newsController.DeleteNews)
router.post('/delete/category/:id', isAdmin, auth, urlencodedParser, newsController.DeleteCategory)

module.exports = router